version: '3.1'

services:
  mongo_1:
    container_name: mongo1
    image: mongo
    command: mongod --replSet rs-1
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - my-mongo-cluster
  mongo_2:
    container_name: mongo2
    image: mongo
    command: mongod --replSet rs-1
    restart: on-failure
    ports:
      - 27018:27017
    networks:
      - my-mongo-cluster
  mongo_3:
    container_name: mongo3
    image: mongo
    command: mongod --replSet rs-1
    restart: on-failure
    ports:
      - 27019:27017
    networks:
      - my-mongo-cluster

networks:
  my-mongo-cluster: